### ISSUE TITLE
Проблемы AR.

### ISSUE THREAD

**Issue by EvgeniiR** [index0h/php-conventions#11]
> Проблема ActiveRecord заключается в том, что помимо данных модель содержит подключение к базе данных, как следствие код, использующий модель получает неявную зависимость от БД, что МОЖЕТ привести к проблемам безопасности. Что бы покрыть unit тестами код, создающий ActiveRecord с большой вероятностью придется менять поведение драйвера подключения к БД, что приведет к крайне высокой сложности.

Не совсем так. Сущности(модели) это часть системы которая содержит самую важную логику(бизнес-правила) и не должна зависеть от модулей которые реализую правила приложения и уж тем более от инфраструктуры(подключение к БД).

Проблема AR в том что сложно покрыть юнитами класс который содержит в себе логику и пишет/читает из БД

Трактовка сущностей как моделей данных это ещё один антипаттерн - https://martinfowler.com/bliki/AnemicDomainModel.html . Он, правда, весьма популярен сейчас. Увы.

**Comment by index0h** [comment]
@EvgeniiR Обычно различают "толстые" и "тонкие" модели, в контексте AR. В обоих случаях unit тесты сложны, со стороны стороннего сервиса. В случае толстых же моделей - еще и велика вероятность получить в результате божественные объекты, а так же ломать голову над тем, как разделить БЛ между двумя и более моделями. То, что в понятия "толстая" Model (AR) иногда трактуется как DomainModel - что поделать))

Как бы вы дополнили этот пункт?

**Comment by EvgeniiR** [comment]
@index0h , 
` в том, что помимо данных ` звучит как-будто модель должа содержать только данные. Это не так. По крайней мере если мы берем полноценную доменную модель как модуль содержащий самую важную для системы БЛ а не анемичную. 
Божественные объекты - бывают, да. Это уже немного о другом и говорит о проблемах с декомпозицией. Я посчитал что это стоит переформулировать.

Если мы рассматриваем т.н. Rich Model + Data Mapper vs AR(который Rich Model + коннект к базе в одном классе), проблема AR в том, что наша бизнес логика что-то знает про базу данных(направление зависимостей), и в том что мы не можем эту самую самую важную бизнес логику тестировать отдельно от базы. 
А проблемы с безопасностью - ну, непонятно...

По поводу тонкого AR. Если мы говорим об AR как о паттерне, а не о фреймворке-реализации, следует различать [AR](https://www.martinfowler.com/eaaCatalog/activeRecord.html) и [Row Data Gateway](https://martinfowler.com/eaaCatalog/rowDataGateway.html). 

`Active Record is very similar to Row Data Gateway (152). The principal difference is that a Row Data
Gateway (152) contains only database access while an Active Record contains both data source and domain
logic. Like most boundaries in software, the line between the two isn't terribly sharp, but it's useful.` - из PoEAA


> а так же ломать голову над тем, как разделить БЛ между двумя и более моделями

Ну да, это непросто. Границы вообще проводить сложно. Но если у нас не будет границ у нас не будет и архитектуры. Так то и SOLID сложно, потому в теории его все знают(читай заучили определение) а на практике и не вспомнят.

**Comment by index0h** [comment]
@EvgeniiR можете провести ревью изменений? #13

**Comment by EvgeniiR** [comment]
@index0h Отписался по поводу текущих изменений, и предложил свою версию правок тут - https://github.com/index0h/php-conventions/pull/14

**Comment by index0h** [comment]
@EvgeniiR Вмерджил, спасибо
