### ISSUE TITLE
1.6. Выделение управляющих инструкций

### ISSUE THREAD

**Issue by peter-gribanov** [index0h/php-conventions#19]
[1.6. Выделение управляющих инструкций](https://github.com/index0h/php-conventions#16-%D0%B2%D1%8B%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D1%8E%D1%89%D0%B8%D1%85-%D0%B8%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D0%B9)

Кажется логичным, но это неправильно. Правильней в блоки группируются логически связанные куски кода, а не формировать блоки на основе синтаксиса языка и разделять логически связанные куски.

Простой пример, получения набора данных и формирование карты данных для быстрого поиска. Вы предлагаете оформить код так:

```php
$articles = $article_rep->match(new PublishedArticles());
$map = [];

foreach ($articles as $article) {
    $map[$article->getId()] = $article;
}
```

Но даже из описания понятно, что у нас есть 2 логических блока которые надо визуально разделять и объявление переменной `$map` относится к блоку формирования карты, а не к блоку получения данных. То есть, правильней писать так:

```php
$articles = $article_rep->match(new PublishedArticles());

$map = [];
foreach ($articles as $article) {
    $map[$article->getId()] = $article;
}
```

**Comment by index0h** [comment]
Тут не совсем согласен. Переменные, вводимые перед управляющими инструкциями очень часто требуются и после этих инструкций.
Для ситуаций, когда переменные носят чисто вспомогательный характер, например таких:

```php
// Тут $currentNotice только обслуживает цикл и далее не используется.
$currentNotice = $this->noticeRepository->findOneUnprocessed();

while (!is_null($currentNotice)) {
    $this->noticeProcessor->process($currentNotice);
    // ...
    $currentNotice = $this->noticeRepository->findOneUnprocessed();
}
```

возможно ваш кейс и валиден, но они встречаются довольно редко. Бывают ситуации когда вспомогательных переменных несколько. Это налагает дополнительные требования к инженеру по разделению переменных на вспомогательные и не вспомогательные.
По этой причине лучше отделять все.

**Comment by peter-gribanov** [comment]
Ну вот в случае с `if` вспомогательных переменных обычно нет и отделять `if` от других частей кода можно и я так регулярно и делаю. У циклов `for`, `foreach`, `while`, `do-while` очень часто бывают вспомогательные переменные и отделять их от цикла неудобно. Поэтому я и говорю, что нужно исходить не из синтаксиса языка, а из логических блоков кода.
Я хочу сделать акцент на том, что блок `if` и логический блок программы это не одно и то же. Да, в большинстве случаев блок с `if` и блок с циклом ли `switch` это логические блоки кода и они автоматически отделяются от остального кода, но это не всегда так.

Вот пример логического блока с `if`:

```php
$video_embed_link = '';
if ($command->video_embed_link) {
    $video_embed_link = $this->converter->pageToEmbed($command->video_embed_link);
}
```

Этот код можно было бы записана в одну строку, но это менее читабельно и мы упираемся в ограничение в 120 символов уже на втором уровне.

```php
$video_embed_link = $command->video_embed_link ? $this->converter->pageToEmbed($command->video_embed_link) : '';
```

> Переменные, вводимые перед управляющими инструкциями очень часто требуются и после этих инструкций.

Если мы вводим переменную и сразу же ее заполняем, то это не отдельный логический блок в большинстве случаев, а часть объявления переменной. Рассматривайте это так:

```php
$ids = [];
foreach ($articles as $article) {
    $ids[] = $article->getId();
}
```

более экономичная версия чем:

```php
$ids = array_map(fn($article) => $article->getId(), $articles);
```

**Comment by peter-gribanov** [comment]
Еще хочу сказать, что `break` и `continue` стоит отделять строкой в контексте циклов, так как это по суть выход из блока как `return`. Но вот в случае `switch` я бы не отделял `break` отдельной строкой. Это делает и так многословный `switch` еще шире и читаемость страдает. Идентифицировать границы блоков удобнее по `case`, а не по отступу перед `break`.
И у вас видимо ошибка [тут](https://github.com/index0h/php-conventions#43-%D0%B8%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D1%8F-switch) или [тут](https://github.com/index0h/php-conventions#71-%D0%BF%D0%BE%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5-%D0%BA%D0%BE%D0%B4%D0%B0).

**Comment by index0h** [comment]
В 4.3 ошибка, поправлю в #21

**Comment by index0h** [comment]
Разделение переменных на вспомогательные и не вспомогательные все же идея не очень.
Пример: у вас есть два цикла, один за другим, переменная используется в обоих и она вспомогательная, по хорошему ее стоит прилепить к первому циклу, но это не совсем корректно.
У вас все без исключения переменные, создаваемые в методе и не являющиеся возвращаемым значением (или бросаемым исключением) - это вспомогательные переменные.
Логические блоки можно выделять и даже нужно, стоит все же концентрировать внимание на самом блоке, а не на дополнительных переменных в них.

С течением времени код рефакторится и модернизируется, что делать с переменной, которая перестала быть вспомогательной, переносить ее выше, а с переменной, которая вдруг стала вспомогательной - переносить ниже?

**Comment by peter-gribanov** [comment]
> Пример: у вас есть два цикла, один за другим, переменная используется в обоих и она вспомогательная, по хорошему ее стоит прилепить к первому циклу, но это не совсем корректно.

Почему нет? Если первый цикл служит для инициализации переменной, то не важно как переменная будет использоваться в дальнейшем, она все равно связана с этим циклом.

Это все равно, что предлагать писать так говоря, что переменная не связана:

```php
$ids = [];

$ids = array_map(fn($article) => $article->getId(), $articles);
// do something
```

Такой подход применим скорей для языков со статической типизацией, когда в начале функции мы декларируем все используемые переменные и их типы, а потом уже пишем код использующий их. В языках с динамической типизацией принято объявлять переменные в контексте их использования. Такой код в языках с динамической типизацией считается плохим:

```php
$i = 0;

for (; $i < 10; $i++) {
    // do something
}
```

> Логические блоки можно выделять и даже нужно, стоит все же концентрировать внимание на самом блоке, а не на дополнительных переменных в них.

Так я об этом и говорю. Не нужно отделять переменные от блока если они являются частью этого блока.

> С течением времени код рефакторится и модернизируется, что делать с переменной, которая перестала быть вспомогательной, переносить ее выше, а с переменной, которая вдруг стала вспомогательной - переносить ниже?

Конечно. В этом и суть рефакторинга. Мне вспоминается фраза Олега Зинченко с [доклада про DDD](https://youtu.be/hqQSN1ndKA8?list=PLRpBLtqfErQDoLLvcgvcNP5KSWqztgOBF&t=2375).

И все же, я повторюсь. В этом пункте нужно говорить не о конструкциях языка. Скорее как-то так:

*Не пишите код программы сплошной портянкой. Такой код тяжело читать. Выделяйте в коде логически связанные блоки и разделяйте их одной пустой строкой как вы отделяете методы одного класса друг от друга.*

***Плохо***

```php
$articles = $article_rep->getLast($limit);
if (!$articles) {
    throw new \Exception('No last articles.');
}
$article_ids = [];
foreach ($articles as $article) {
    $article_ids[] = $article->getId();
}
$comments = $comment_rep->getByArticleIds($article_ids);
```

***Хорошо***

```php
$articles = $article_rep->getLast($limit);

if (!$articles) {
    throw new \Exception('No last articles.');
}

$article_ids = [];
foreach ($articles as $article) {
    $article_ids[] = $article->getId();
}

$comments = $comment_rep->getByArticleIds($article_ids);
```

<details>
  <summary>Пояснение с комментариями</summary>

```php
// блок получения списка статей
$articles = $article_rep->getLast($limit);

// блок проверки списка статей
if (!$articles) {
    throw new \Exception('No last articles.');
}

// блок получения списка ID статей
$article_ids = [];
foreach ($articles as $article) {
    $article_ids[] = $article->getId();
}

// блок получения всех комментариев для выбранных статей
$comments = $comment_rep->getByArticleIds($article_ids);
```
</details>

**Comment by index0h** [comment]
> Почему нет? Если первый цикл служит для инициализации переменной, то не важно как переменная будет использоваться в дальнейшем, она все равно связана с этим циклом.

Потому, что переменная связана с двумя циклами, объединяя ее с одним мы указываем на то, что переменная связана именно с этим циклом, что не корректно.

> Не пишите код программы сплошной портянкой. Такой код тяжело читать. Выделяйте в коде логически связанные блоки и разделяйте их одной пустой строкой как вы отделяете методы одного класса друг от друга.

Дык я и не предлагаю писать портянкой, данные и обработку отделяем пустыми строками.
Если честно я до сих пор не вижу, чем ваш пример

```php
$articles = $article_rep->getLast($limit);

if (!$articles) {
    throw new \Exception('No last articles.');
}

$article_ids = [];
foreach ($articles as $article) {
    $article_ids[] = $article->getId();
}

$comments = $comment_rep->getByArticleIds($article_ids);
```

более читабелен, чем такой

```php
$articles = $article_rep->getLast($limit);

if (!$articles) {
    throw new \Exception('No last articles.');
}

$article_ids = [];

foreach ($articles as $article) {
    $article_ids[] = $article->getId();
}

$comments = $comment_rep->getByArticleIds($article_ids);
```

Следующий пример вполне читаем, тут и break отдельно и $id отдельно.

```php
/**
 * @return Transaction[]
 */
public function closeUnfinishedTransactions(
    \DateTimeImmutable $closedAt,
    Reason $reason,
    Transaction ...$transactions,
    ?string $token
): array {
    // ...

    foreach ($transactions as $transaction) {
        $id = $transaction->getId();

        switch ($transaction->getType()->getValue()) {
            case TransactionType::FIRST:
                $this->firstTransactionCloseProducer->publish($id, $reason, $closedAt);

                break;
            case TransactionType::SECOND:
                $this->secondTransactionCloseProducer->publish($id, $reason, $closedAt);

                break;
            case TransactionType::THIRD:
                $this->thirdTransactionCloseProducer->publish($id, $reason, $closedAt, $token);

                break;
        }
    }

    return $transactions;
}
```

Чем он хуже, чем оформленный, согласно вашим предложениям?

```php
/**
 * @return Transaction[]
 */
public function closeUnfinishedTransactions(
    \DateTimeImmutable $closedAt,
    Reason $reason,
    Transaction ...$transactions,
    ?string $token
): array {
    // ...

    foreach ($transactions as $transaction) {
        $id = $transaction->getId();
        switch ($transaction->getType()->getValue()) {
            case TransactionType::FIRST:
                $this->firstTransactionCloseProducer->publish($id, $reason, $closedAt);
                break;
            case TransactionType::SECOND:
                $this->secondTransactionCloseProducer->publish($id, $reason, $closedAt);
                break;
            case TransactionType::THIRD:
                $this->thirdTransactionCloseProducer->publish($id, $reason, $closedAt, $token);
                break;
        }
    }

    return $transactions;
}
```

**Comment by peter-gribanov** [comment]
> Потому, что переменная связана с двумя циклами, объединяя ее с одним мы указываем на то, что переменная связана именно с этим циклом, что не корректно.

Переменная не связана с 2 циклами. Она связана с одним циклом, а во втором она используется.

Проблема в том, что в данном контексте объявление переменной `$article_ids` не выглядит как самостоятельный логический блок.

```php
$articles = $article_rep->getLast($limit);

if (!$articles) {
    throw new \Exception('No last articles.');
}

// что это за логический блок?
$article_ids = [];

foreach ($articles as $article) {
    $article_ids[] = $article->getId();
}

$comments = $comment_rep->getByArticleIds($article_ids);
```
Я предлагаю и практикую такое оформление кода

```php
/**
 * @return Transaction[]
 */
public function closeUnfinishedTransactions(
    \DateTimeImmutable $closedAt,
    Reason $reason,
    Transaction ...$transactions,
    ?string $token
): array {
    // ...

    foreach ($transactions as $transaction) {
        $id = $transaction->getId();

        switch ($transaction->getType()->getValue()) {
            case TransactionType::FIRST:
                $this->firstTransactionCloseProducer->publish($id, $reason, $closedAt);
                break;
            case TransactionType::SECOND:
                $this->secondTransactionCloseProducer->publish($id, $reason, $closedAt);
                break;
            case TransactionType::THIRD:
                $this->thirdTransactionCloseProducer->publish($id, $reason, $closedAt, $token);
                break;
        }
    }

    return $transactions;
}
```
В данном случае, объявление переменной `$id` не связано со `switch`. Она только используется в нем.

В общем, это видимо слишком сложная грань связанности и не связанности. Проще писать всегда отдельно и не парится на этот счет. Можете оставить это раздел как есть если считаете нужным.
