### ISSUE TITLE
2.2. Дублирование типов в docblock

### ISSUE THREAD

**Issue by peter-gribanov** [index0h/php-conventions#20]
[2.2. Дублирование типов в docblock](https://github.com/index0h/php-conventions#22-%D0%B4%D1%83%D0%B1%D0%BB%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D1%82%D0%B8%D0%BF%D0%BE%D0%B2-%D0%B2-docblock)

Очень популярное решение, особенно в связи с вводом [type hinting в PHP](https://www.php.net/manual/ru/functions.arguments.php#functions.arguments.type-declaration) для базовых типов. В [Symfony](https://github.com/symfony/symfony) уже давно практикуют этот подход и недавно включили правило для этого кейса в [PHP CS Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer).

Я безусловно согласен с тем, что дублирование типов в аннотациях бессмысленно и логично описывать только те типы которые нельзя задекларировать средствами языка. Однако, на мой взгляд, это затрудняет восприятие и чтение кода и на то есть 2 причины:

1. Блок комментариев перед методом визуально отделяет конец одного метода и начало второго. По широкой зелёной полосе очень хорошо ориентироваться в границах методов при беглом просмотре класса. По блоку аннотаций легко найти начало метода. Код класса вообще без комментариев превращается в лапшу и читать его субъективно тяжелее.
2. В случае описания полного списка принимаемых и возвращаемых значений в DocBlock, у нас есть 2 места где мы декларируем типы, это в аннотациях и в коде метода. В аннотациях описание более полное поэтому мы читаем только аннотации. Если в аннотациях описание неполное, то мы вынуждены читать как аннотации так и декларацию в коде. То есть, читать нужно одновременно в 2 местах и переключатся между разными формами декларации типов. Особенно это неудобно если в аннотациях кастомизирован тип одного или нескольких аргументов метода из середины большого списка аргументов. Выигрыш мы получаем только если у нас вообще нет кастомизации типов в аннотациях.

```php
/**
 * @param Articles[] $third
 */
public function example(string $first, ?int $second, array $third, bool $fourth = false, float ...$fifth): string
```

Еще больше усугубляется проблема если мы начинаем использовать свои PHPDoc-теги статических анализаторов типа [Psalm](https://github.com/vimeo/psalm) и [Phan](https://github.com/phan/phan).

```php
/** 
 * @param array $parsed_url
 * @phan-param array{scheme:string,host:string,path:string} $parsed_url
 * @psalm-param array{scheme:string,host:string,path:string} $parsed_url  
*/
public function showUrl(string $label, array $parsed_url, string $host): string
```

Еще страннее выглядит кейс когда мы добавляем описание аргумента функции в DocBlock, которое должны были бы удалить, только для того, что бы добавить комментарий для этого аргумента.

```php
/**
 * @param string $controller The controller name (a string like Bundle\BlogBundle\Controller\PostController::indexAction)
 */
protected function forward(string $controller, array $path = [], array $query = []): Response
{
    $request = $this->container->get('request_stack')->getCurrentRequest();
    $path['_controller'] = $controller;
    $subRequest = $request->duplicate($query, null, $path);

    return $this->container->get('http_kernel')->handle($subRequest, HttpKernelInterface::SUB_REQUEST);
}
```
Лично мне эта частичная аннотация не нравится. Либо мы описываем все, либо ничего. Полумеры я не готов принимать, по крайней мере сейчас.

**Comment by index0h** [comment]
Перед тем, как вводилось подобное правило на моем прошлом проекте, я тоже был очень скептичен. Что касается привыкания глаз к такому подходу - несколько дней, и отсутствие разделителя комментарием перестает быть проблемой.
Я очень часто сталкивался с проблемой, когда аннотация не соответствует тайпхинтингу, или в случае когда тайпхинтинг не применим - реальным требованиям к аргументу/результату, от части это правило должно решать эту проблему.
Что касается psalm/phan - годный комментарий, оговорку про допущение подобных ситуаций для внешних систем, обрабатывающих аннотации добавлю.

**Comment by peter-gribanov** [comment]
Свои DocBlock теги есть ещё и у [PHPStan](https://medium.com/@ondrejmirtes/generics-in-php-using-phpdocs-14e7301953).

**Comment by index0h** [comment]
Правки по разрешению дублирующих аннотаций для внешних систем и комментариев добавил, по этому закрываю задачу
