### ISSUE TITLE
2.6. Свойства

### ISSUE THREAD

**Issue by peter-gribanov** [index0h/php-conventions#25]
[2.6. Свойства](https://github.com/index0h/php-conventions#26-%D1%81%D0%B2%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%B0)

Для свойств класса принято использовать многосточный DocBlock.

https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Controller/AbstractController.php#L59

```php
/**
 * @var string[]|null
 */
private $names;

/**
 * @var int|null
 */
private $count;
```

Смотрите правило `phpdoc_line_span` в [PHP CS Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer).

**Comment by index0h** [comment]
Это требование было введено потому, что в большинстве случаев вам в многострочных докблоках для переменных нет ни какой необходимости, они просто занимают место.
Для случаев, когда нужно добавить многострочный комментарий, или дополнительных аннотаций добавить - безусловно, однострочным док блоком обойтись не получится, **этот комментарий я добавлю**.
Понимаете, когда у вас класс например на 20 свойств - это чуть больше 1 экрана, если же использовать многострочные - тут 2 экрана, причем существенная часть этих данных - в принципе не несут ни какой информации.
То, что в PHP CS Fixer, или Symfony так по умолчанию - да не вопрос, в этих проектах свои требования, тут - свои. Что первые, что вторые - спецификацию phpdoc не нарушают.
Я только что пробежался по https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md требования мультистрочных докблоках для свойств не обнаружил.

Однострочные докблоки для свойств полностью аналогичны однострочным докблокам для переменных внутри метода. Это еще одна из причин.

**Comment by peter-gribanov** [comment]
К вопросу о докблоках у переменных. У статических анализатор бывают проблемы с анализом их. Лучше избегать использовать аннотации для переменных если вы планируете использовать статические анализаторы.

**Comment by index0h** [comment]
> К вопросу о докблоках у переменных. У статических анализатор бывают проблемы с анализом их.

Пока не сталкивался, можно пример?

**Comment by index0h** [comment]
комментарий про многострочный докблок добавил
