### ISSUE TITLE
3.7. Модификаторы доступа для методов

### ISSUE THREAD

**Issue by peter-gribanov** [index0h/php-conventions#28]
[3.7. Модификаторы доступа для методов](https://github.com/index0h/php-conventions#37-%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80%D1%8B-%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%B0-%D0%B4%D0%BB%D1%8F-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%BE%D0%B2)

Аналогично с пунктом 3.4 #26 

Есть кейсы для которых удобно использовать статические методы. Например фабрики:

* https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Exception/MissingIdentifierField.php
* https://github.com/jupeter/clean-code-php/issues/172
* https://github.com/gpslab/enum
* https://github.com/marc-mabe/php-enum/
* https://github.com/antanas-arvasevicius/enumerable-type

**Comment by index0h** [comment]
Удобно - вовсе не значит поддерживаемо, тестируемо, расширяемо.
Про enum я уже писал, фабричные методы не нужны, достаточно конструктора и констант.
На счет других кейсов - в чем проблема, создаем класс фабрику и радуемся жизни.

То, что в доктрине хэлпер для исключения создали - очень так себе аргумент, переопределить конструктор в такой ситуации - вполне отличная альтернатива, учитывая, что сигнатуры в \LogicalException и MissingIdentifierField отличаются друг от друга.

Еще раз, бывают исключительные ситуации, когда без статики ну вот вообще ни как, на этот случай есть пункт ЗС. Разница только в том, что таких ситуаций очень мало.

Поймите правильно, вот эти рекомендации - это не про сиесекундное удобство. Эти рекомендации про: читаемость, поддерживаемость, тестируемость и расширяемость.

В одном из моих проектов тоже есть статический метод: https://github.com/ko-ko-ko/php-assert/blob/master/src/Assert.php#L68
Тут используется ЗС по конкретной причине: одно из требований к проекту - время выполнения, сравнимое с нейтивным кодом. Вызов конструктора и создание нового объекта - это слишком долго. На сколько помню, статический метод - x7 от нейтивных проверок, конструктор - x20.

**Comment by peter-gribanov** [comment]
> Про enum я уже писал, фабричные методы не нужны, достаточно конструктора и констант.

Недостаточно, поэтому такие проекты и существуют.
https://3v4l.org/KCoSP

> То, что в доктрине хэлпер для исключения создали - очень так себе аргумент, переопределить конструктор в такой ситуации - вполне отличная альтернатива, учитывая, что сигнатуры в \LogicalException и MissingIdentifierField отличаются друг от друга.

Такой подход применяют не только в Doctrine, но и в ряде других крупных популярных проектах. Объявление сообщений в конструкторе накладывает кучу ограничений. Например мы вынуждены создавать отдельный тип исключения на каждое сообщение. Если есть несколько исключений одного типа, но с разными сообщениями приходится вводить родительский метатип исключения.
В Symfony не используют подход с фабричными методами и исключения пишут в одну строку и в результате инициализация никогда не укладывается в 120 символов. Они для этого даже специальный хук используют в PHP CS Fixer.
А если для формирования сообщения исключения нужна некая логика, то она отъедает пространство в месте формирования и засоряет логику. Поэтому инкапсуляция инициализации исключения позволяет отделять логику программы от логики исключений и делает код более читаемым.

Кстати, в PHPUnit тоже используется static:
https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/TestCase.php

> Поймите правильно, вот эти рекомендации - это не про сиесекундное удобство. Эти рекомендации про: читаемость, поддерживаемость, тестируемость и расширяемость.

Вот я читаю ваши рекомендации и они выглядят не, как рекомендации, а как четкий свод правил, как PSR. Слова НЕОБХОДИМО, ДОЛЖНО, ТРЕБУЕТСЯ, НУЖНО, НЕ ПОЗВОЛЯЕТСЯ не выглядят как рекомендации. Поэтому я и придираюсь, особенно к тем местам где вместо СЛЕДУЕТ, написано ДОЛЖНО. Ещё хочется про CamelCase сказать, но не буду.

PS: Наверное я зря затеял всю эту дискусию. Мы явно не придем к общему консенсусу ибо у нас совершенно разные взгляды. Спасибо за уделённое время и извините если мои слова были грубы или чем-то вас обидели. Предлагаю на это закончить. Спасибо за внимание.

**Comment by index0h** [comment]
> Например мы вынуждены создавать отдельный тип исключения на каждое сообщение.

Этого подхода стоит придерживаться. Как минимум есть возможность заюзать множественные catch и не изобретать вундерфвалю с errorCode. Это бывает очень полезно.

> Если есть несколько исключений одного типа, но с разными сообщениями приходится вводить родительский метатип исключения.

Если сообщения одинаковы структурно и отличаются например только названием переменной, с которой пошел сбой - возможно стоит сделать это одним классом исключений, тогда дополнительный родительский не потребуется.

> В Symfony не используют подход с фабричными методами и исключения пишут в одну строку и в результате инициализация никогда не укладывается в 120 символов.

Такое иногда случается. Когда у вас для каждого случая свое исключение например как тут https://github.com/ko-ko-ko/php-assert/tree/master/src/exceptions проблема с длинными строками возникает очень редко.

> А если для формирования сообщения исключения нужна некая логика, то она отъедает пространство в месте формирования и засоряет логику.

Переносим логику по форматированию сообщения исключения в конструктор исключения и ни каких проблем.

> Кстати, в PHPUnit тоже используется static

Знаю, но использую вызовы методов из TestCase через $this.

> Вот я читаю ваши рекомендации и они выглядят не, как рекомендации, а как четкий свод правил, как PSR

Верно случае только рекоммендаций как мне стоит разделять то, что важно, и просто желательно, либо не обязательно. Исходя из этих соображений я решил не изобретать велосипед и использовать устоявшуюся терминологию.

@peter-gribanov Что вы, вовсе не зря, вы указали на многие неточности, за что вам огромное спасибо. На счет слов, которые могут обидеть - проблем не вижу вовсе, если я выражаюсь слишком резко - извините.

**Comment by peter-gribanov** [comment]
> Если сообщения одинаковы структурно и отличаются например только названием переменной, с которой пошел сбой - возможно стоит сделать это одним классом исключений, тогда дополнительный родительский не потребуется.

А если исключения одинаковые по сути, но с разными сообщениями, разным набором параметров (переменных) и разным типом переменных, то упаковать все в один конструктор ни как не получится. Придется создавать разные классы для исключений и только общий родитель или множественный catch позволят нам одинаково отреагировать на однотипное исключение.

> Когда у вас для каждого случая свое исключение например как тут https://github.com/ko-ko-ko/php-assert/tree/master/src/exceptions проблема с длинными строками возникает очень редко.

Многовато у вас исключений. Вы в них не путаетесь? Я лично думал о том, что бы на каждый тип ошибки создавать свой тип исключения, но получается слишком много объектов. Это прям какой-то Exception менеджмент. В популярных проектах я такого не встречал. Обычно используют ограниченный набор исключений и просто меняют сообщение на входе.

В Symfony проблема с длинной сообщений бывает очень часто, потому, что они очень любят многословные сообщения. Что, почему, от чего и что с этим делать. Сам я с этой проблемой крайне редко сталкиваюсь.

**Comment by index0h** [comment]
> с разными сообщениями, разным набором параметров (переменных) и разным типом переменных, то упаковать все в один конструктор ни как не получится

Это зависит от уровня общности. Фабрику для исключений с текстовками конечно можно сделать, правда нужно ли это - очень зависит от ситуации. Множество классов исключений - это просто универсальный подход.

> Многовато у вас исключений. Вы в них не путаетесь?

Не путаюсь, собственно так же как в множестве классов, методов и свойств.

> Я лично думал о том, что бы на каждый тип ошибки создавать свой тип исключения, но получается слишком много объектов.

Ничего не бывает бесплатно.

> В популярных проектах я такого не встречал.

Во многих популярных проектах на валидацию данных кладется болт, что печально.
В том же predis что будет, если я массив аргументов задам как массив исключений? Для команд, не использующих аргументов вероятно ничего, несмотря на то, что вызов не правильный. Для команд, использующих аргументы - хз, где-то в дебрях не сработает преобразование в строку в лучшем случае.

> Обычно используют ограниченный набор исключений и просто меняют сообщение на входе.

Для ситуаций, когда исключение прям уникальное - вполне годный кейс. Для исключений типа 'аргумент $argumentName должен быть не null' - вполне имеет смысл написать сове исключение и не писать каждый раз такую же текстовку.
