### ISSUE TITLE
4.5. Ошибки

### ISSUE THREAD

**Issue by peter-gribanov** [index0h/php-conventions#30]
[4.5. Ошибки](https://github.com/index0h/php-conventions#45-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8)

За исключением `E_USER_DEPRECATED`.

* https://github.com/twigphp/Twig/blob/v2.7.0/lib/Twig/Compiler.php#L7
* https://github.com/Happyr/Doctrine-Specification/blob/master/src/Specification/Having.php#L20

Аналогичный подход применяется во многих популярных проектах.

**Comment by index0h** [comment]
Этот подход применяется не от хорошей жизни. В ваших примерах - это уведомление об устаревших методах/классах с надеждой на то, что вывод ошибок не отключен и конечный инженер увидев подобное примет какие-то действия, после обновления зависимостей.

Решение очень спорное. Если ломается обратная совместимость - по хорошему достаточно добавить `@deprecated` аннотации к тому, что устарело и будет выпилено. Если такие действия конечным пользователем пакета проигнорированы - ну что ж, с обновлением мажорной версии его ждет сюрприз.

В случаях, что вы привели: обратная совместимость ломается 2 раза. Первый раз при добавлении error, второй раз при удалении устаревшего.

**Comment by peter-gribanov** [comment]
Аннотации не слишком надёжный способ. А ошибки которые спамят в лог это по сути ещё один способ донести информацию до пользователя. 

> В случаях, что вы привели: обратная совместимость ломается 2 раза. Первый раз при добавлении error, второй раз при удалении устаревшего.

Скорей при удалении, а не при добавлении error. При мажорном обновлении удаляется метод и его содержимое, в том числе error в методе. Тоже касается классов. Удаляется файл вместе с классом объявлено в нем и всем остальным.

**Comment by peter-gribanov** [comment]
Вы можете не принимать этот подход, но это best practice.

**Comment by index0h** [comment]
Все же этот подход принять не могу.
Подобная практика безусловно может использоваться, но должна регламентироваться дополнительными соглашениями на проекте.
