### ISSUE TITLE
4.13. Магические методы

### ISSUE THREAD

**Issue by peter-gribanov** [index0h/php-conventions#31]
[4.13. Магические методы](https://github.com/index0h/php-conventions#413-%D0%BC%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B)

Использование магических методов типа `__call`, `__callStatic`, `__get` и `__set` допускается, но при обязательном описании списка доступных методов и свойств в аннотациях. Пример: https://github.com/nrk/predis/blob/v1.1/src/ClientInterface.php

**Comment by index0h** [comment]
Плохо, очень плохо. Подобная штука есть еще в https://github.com/guzzle/guzzle .

Дает ли магия тут какие-то прям небывалые профиты - вообще-то нет. Если вы задумались про DRY - то вот как раз в таких ситуациях он вреден, команды редиски не зависят друг от друга.

Вместо того, что бы использовать нейтивные средства и корректно описать интерфейс клиента используются докблоки, не являющиеся нейтивными средствами языка.

Так же мокать в тестах подобное - не геморно.

**Comment by peter-gribanov** [comment]
> Дает ли магия тут какие-то прям небывалые профиты - вообще-то нет.

Вообще то да. Дублирование однотипных методов в данном случае ни каких преимуществ не даёт.
Аналогичный кейс здесь, список методов неизвестен заранее и автоматически генерируемые методы позволяют в разы упростить клиентский код. А мокать генерируемые методы не нужно так как это VO.
https://github.com/gpslab/enum

**Comment by index0h** [comment]
> Вообще то да. Дублирование однотипных методов в данном случае ни каких преимуществ не даёт.

Не согласен. Если описывается интерфейс, который должен содержать N методов - нужно описать N методов.

> Аналогичный кейс здесь, список методов неизвестен заранее и автоматически генерируемые методы позволяют в разы упростить клиентский код.

Известны, и аргументы известны, что тогда делают аннотации `@method` в интерфейсе ClientInterface?

> А мокать генерируемые методы не нужно так как это VO.

Я говорил в контексте клиента, что predis, что guzzle. Мокать в тестах их методы очень даже полезно.

**Comment by peter-gribanov** [comment]
> Известны, и аргументы известны, что тогда делают аннотации @method в интерфейсе ClientInterface?

Я говорил про библиотеки для работы с enum. Список значений задаёт клиент, а интерфейс доступа предоставляет библиотека.

> Я говорил в контексте клиента, что predis, что guzzle. Мокать в тестах их методы очень даже полезно.

Ни что не мешает замолкать магические методы. Не помню, что бы с этим были проблемы. Интерфейс немного другой, вот и вся разница.

**Comment by index0h** [comment]
> Я говорил про библиотеки для работы с enum. Список значений задаёт клиент, а интерфейс доступа предоставляет библиотека.

Учитывая, что это просто VO, можно объявить у себя нечто типа такого и отпочковывать только классы с константами. Если прям очень надо - можно получение констант вынести в публичный, или защищенный отдельный метод.

<details>
  <summary>VO для int</summary>

```php

abstract class AbstractIntValueObject
{
    /** @var int */
    private $value;

    public function __construct(int $value)
    {
        $this->validate($value);

        $this->value = $value;
    }

    public function getValue(): int
    {
        return $this->value;
    }

    /**
     * @param object|int $value
     */
    public function equals($value): bool
    {
        if (is_int($value)) {
            return $this->getValue() === $value;
        } elseif (is_object($value) && $value instanceof AbstractIntValueObject) {
            return $this->getValue() === $value->getValue();
        }

        throw new \InvalidArgumentException(
            sprintf('Equality allowed only for objects, integers, "%s" given', gettype($value))
        );
    }

    public function __toString(): string
    {
        $constants = (new \ReflectionClass(static::class))->getConstants();

        $constantName = array_search($this->getValue(), $constants);

        if ($constantName !== false) {
            return sprintf('%s[%s]', $constantName, $this->getValue());
        }

        return '';
    }

    protected function validate(int $value): void
    {
        if (!is_string($value) && !is_int($value)) {
            throw new \InvalidArgumentException(
                sprintf(
                    'Value must be of string or int type, "%s" given',
                    gettype($value)
                )
            );
        }

        $values = array_values((new \ReflectionClass(static::class))->getConstants());

        if (in_array($value, $values, true) === false) {
            throw new InvalidValueObjectValueException($value, $values);
        }
    }
}
```

</details>

> Ни что не мешает замолкать магические методы. Не помню, что бы с этим были проблемы. Интерфейс немного другой, вот и вся разница.

Я не говорю, что это не возможно. Это затрудняет чтение, так как для двух и более вызовов разных методов, я мокаю один и тот же метод.

**Comment by peter-gribanov** [comment]
> Учитывая, что это просто VO, можно объявить у себя нечто типа такого и отпочковывать только классы с константами.

Я вам не просто так приводил этот пример:
https://3v4l.org/KCoSP

Ваш пример недоработан:

```php
class Foo extend AbstractIntValueObject
{
    public const A = 1;
    public const B = 2;
}
class Bar extend AbstractIntValueObject
{
    public const X = 1;
    public const Y = 2;
}

var_dump(new Foo(Foo::A) === new Foo(Foo::A)); // false
var_dump((new Foo(Foo::A))->equals(Bar::X)); // true
var_dump((new Foo(Foo::A))->equals(new Bar(Bar::X))); // true
```

Та же проблема есть и в [SPL](https://github.com/gpslab/enum#splenum).

Частично это можно исправить, но идентичность объектов можно исправить только контролем за инстансами объекта, а это можно сделать только через статические методы и свойства.

Плюс, вы через рефлексию получаете список констант при каждом создании объекта. Это расточительно. Лучше один раз прочитать список констант и закешировать его, а для этого опять нужны статические свойства. Не пихать же DI в VO.

А магические методы нужны для удобства. Большинство проектов предлагающих реализацию enum позволяют создавать инстансы без магии.

```php
$permission = Permission::byValue(Permission::AWAITING);
// или короче
$permission = Permission::awaiting();

if ($permission->equals(Permission::byValue(Permission::AWAITING)) {
    // ...
}

// или короче

if ($permission->isAwaiting()) {
   // ...
}
```

**Comment by index0h** [comment]
> Плюс, вы через рефлексию получаете список констант при каждом создании объекта. Это расточительно.

Я не просто так написал про то, что список значений можно переопределить и например возвращать из константы в стиле `private const ALL_VALUES = [...];` в этом случае будет передана всего навсего ссылка на массив.

Что же касается сравнения объектов - можно заюзать ЗС для конкретно VO, либо принять соглашение: VO сравниваются только с помощью метода equals.

**Comment by peter-gribanov** [comment]
> список значений можно переопределить и например возвращать из константы

> VO сравниваются только с помощью метода equals

Это всё ухищрения, такие же как магические методы. Какой из способов лучше применять надо решать на конкретном проекте, в конкретной команде. Многие считают, что использование магических и статических методов не зазорно и профитно. Вы считаете иначе. Ваше право.

**Comment by index0h** [comment]
> Многие считают, что использование магических и статических методов не зазорно и профитно. Вы считаете иначе. Ваше право.

Все верно. Этот проект не является серебрянной пулей, но помочь в разработке может. Если в конечной команде какой-то из пунктов считается не корректным, проект спокойно форкается, то что не нравится - вырезается.

Что же касается именно магии, как показывает мой опыт, чем крупнее/сложнее проект - тем магия опаснее. По этой причине этот скоуп рекомендаций и запрещает энтропию подобного рода.
