### ISSUE TITLE
7.3. Разделение тест методов

### ISSUE THREAD

**Issue by peter-gribanov** [index0h/php-conventions#32]
[7.3. Разделение тест методов](https://github.com/index0h/php-conventions#73-%D1%80%D0%B0%D0%B7%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%82%D0%B5%D1%81%D1%82-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%BE%D0%B2)

> Каждый тест метод ДОЛЖЕН быть полностью независим от других тест методов.

Тестируемый код может быть зависим от других методов, соответственно и тесты будут зависеть.
https://phpunit.readthedocs.io/ru/latest/writing-tests-for-phpunit.html

**Comment by index0h** [comment]
Тут конфликт трактовок "независимость тестов". `@depends` влияет на запуск тестов, в моем же случае - это не зависимость кода теста от кода других тестов. Этот момент я дополню.

Пример: тестА создает какое-то состояние в тест кейсе, в этом же тест кейсе тестБ использует то же состояние. Фактически тестБ зависит от тестА и наоборот. В такой ситуации могут быть ложно позитивные и ложно негативные срабатывания.

**Comment by peter-gribanov** [comment]
А, то есть это о том, что тесты не должны сохранять состояние и передавать его другим тестам.

**Comment by index0h** [comment]
Грубо говоря да

**Comment by index0h** [comment]
комментарий добавил
