### ISSUE TITLE
Не правильно

### ISSUE THREAD

**Issue by stdmitry** [index0h/php-conventions#47]
Наречие “неправильно” в значении “ошибочно” пишется слитно – неправильно.

Наречие “не правильно”, если рядом есть местоимение либо наречие с отрицанием, а также слова “отнюдь”, “вовсе”, “далеко” пишется раздельно – не правильно.

https://obrazovaka.ru/kak-pishetsya/nepravilno.html

**Comment by index0h** [comment]
спасибо за таск, пофикшено
